azs:
- name: z1

vm_types:
- name: default

disk_types:
- name: default
  disk_size: 1024

compilation:
  workers: 5
  az: z1
  reuse_compilation_vms: true
  vm_type: default
  network: default

networks:
- name: default
  type: manual
  subnets:
    - azs: [z1]
      range: 10.244.123.0/24
      reserved: [10.244.123.1]
      static: [10.244.123.34]

- name: blacksmith
  type: manual
  subnets:
    - azs: [z1]
      range: 10.244.51.0/24
      reserved: [10.244.51.1]
      static: [10.244.51.34]